- name: Install apache packages
  apt: name={{ item }} state=present
  with_items:
    - apache2
    - python
    - libapache2-mod-wsgi
    - libmysqlclient18
    - libmysqlclient-dev
    - mysql-client

- name: Disable unused apache modules
  command: a2dismod autoindex cgi env

- name: copy Apache vhost file
  template:
    src=os/etc/apache2/sites-available/support.conf
    dest=/etc/apache2/sites-available/support.conf
    owner=root
    group=root
    mode=0644

- name: Make the support directory
  file: dest=/var/www/support owner=www-data group=www-data state=directory

- name: Copy support website
  template:
    src=os/var/www/support/index.html
    dest=/var/www/support/index.html
    owner=www-data
    group=www-data

- name: Enable apache2 site
  command: a2ensite support
  notify:
    - restart apache
